### ISSUE TITLE
Aliyun.Credentials 更新 1.4.3 后 AlibabaCloud.OpenApiClient 无法正常实例化，报错 System.MissingMethodException

### ISSUE THREAD

**Issue by nidbCN** [aliyun/credentials-csharp#52]
在执行如下代码时引发：

```cs

        _apiClient = new(new()
        {
            Endpoint = options.Value.Endpoint,
            Credential = credentialClient,
        });
```

堆栈信息：
```
Unhandled exception. System.MissingMethodException: Method not found: 'Void Aliyun.Credentials.Client..ctor(Aliyun.Credentials.Models.Config)'.
    at AlibabaCloud.OpenApiClient.Client..ctor(Config config)
    at AlibabaCloud.SDK.Cdn20180510.Client..ctor(Config config)
    at AliCdnSSLWorker.Services.AliCdnService..ctor(ILogger`1 logger, IOptions`1 options) in /src/Services/AliCdnService.cs:line 28
```

通过查看堆栈信息，问题由 `AlibabaCloud.OpenApiClient.Client..ctor(Config config)` 引发，可能是该库内调用 `this._credential = new Aliyun.Credentials.Client(credentialConfig);` 时候，无法找到接收参数为 Config 的构造函数。

看了源码之后有些奇怪的，为什么不重载构造函数？

不过我也很奇怪，即使是现在这样，也应该能够擦除到 `object` 才对啊？

似乎应该在 darabonba-openapi 开 issue，但是考虑到如果确实是因为构造函数接收的参数从 `Config config` 到 `object obj` 引发的问题，那应该在其他一些 SDK 中也存在，所以我先来这边开个 issue 问下，至于是这个 SDK 更新的问题还是 darabonba-openapi 没有更新调用的方法还看你们怎么解决了。如果我不该在这里开 issue 的话还请提示我一下，谢谢

**Comment by PanPanZou** [comment]
您好，感谢反馈。
第一个问题是因为重载构造函数会导致传null时无法区分是Config还是IAlibabaCloudCredentialsProvider。
第二个问题是因为OpenApiClient中的依赖的Credentials版本为1.4.2，您这边是否在项目中直接依赖了Credentials的1.4.3版本，此时编译时使用的仍是 public Client(Config config) 的声明，运行时会依赖到更新后的public Client(Object obj)，从而导致报错Method not found。待升级OpenApiClient中的Credentials版本升级后就不会报错了。
